import React, { createContext, useContext, useState, useEffect } from 'react';

const LanguageContext = createContext();

export const useLanguage = () => {
  const context = useContext(LanguageContext);
  if (!context) {
    throw new Error('useLanguage must be used within a LanguageProvider');
  }
  return context;
};

const translations = {
  en: {
    // Navigation
    nav: {
      home: 'Home',
      about: 'About',
      sermons: 'Sermons',
      events: 'Events',
      ministries: 'Ministries',
      give: 'Give',
      contact: 'Contact',
      getInvolved: 'Get Involved',
      watchLive: 'Watch Live',
    },
    // Home Page
    home: {
      welcome: 'Welcome to',
      churchName: 'Movement Church',
      tagline: 'Teaching the Commands of Jesus Christ',
      mission: 'We believe in the Great Commission',
      joinUs: 'Join Us',
      watchOnline: 'Watch Online',
      sundayService: 'Sunday Service',
      serviceTime: '10:00 AM Every Sunday',
      serviceLocation: 'Fourth Avenue, Masotsha Ndlovu Way, Parktown',
      liveNow: 'Live Now',
      upcomingEvents: 'Upcoming Events',
      latestSermons: 'Latest Sermons',
      ourMission: 'Our Mission',
      missionText: 'We are committed to teaching the commands of Jesus Christ and fulfilling the Great Commission by making disciples of all nations.',
      getConnected: 'Get Connected',
      connectText: 'Join us in worship, fellowship, and serving our community.',
      visitUs: 'Visit Us',
    },
    // About Page
    about: {
      title: 'About Movement Church',
      subtitle: 'Our Story, Vision & Values',
      ourStory: 'Our Story',
      storyText: 'Movement Church was founded with a passion to see lives transformed by the power of the Gospel. We are a community of believers committed to following Jesus Christ and living out His commands.',
      ourVision: 'Our Vision',
      visionText: 'To be a movement of disciples making disciples, teaching and living out the commands of Jesus Christ in our community and beyond.',
      ourValues: 'Our Values',
      value1: 'Great Commission',
      value1Text: 'We are committed to fulfilling the Great Commission by making disciples of all nations.',
      value2: 'Biblical Teaching',
      value2Text: 'We teach and obey the commands of Jesus Christ as revealed in Scripture.',
      value3: 'Community',
      value3Text: 'We believe in authentic fellowship and caring for one another.',
      value4: 'Service',
      value4Text: 'We serve our community and the world with the love of Christ.',
      leadershipTeam: 'Leadership Team',
      meetOurPastors: 'Meet Our Pastors',
    },
    // Sermons Page
    sermons: {
      title: 'Sermons',
      subtitle: 'Watch and listen to messages that transform lives',
      latest: 'Latest Message',
      allSermons: 'All Sermons',
      watchNow: 'Watch Now',
      series: 'Series',
      speaker: 'Speaker',
      date: 'Date',
      duration: 'Duration',
      categories: 'Categories',
    },
    // Events Page
    events: {
      title: 'Events',
      subtitle: 'Join us for upcoming events and gatherings',
      upcoming: 'Upcoming Events',
      past: 'Past Events',
      when: 'When',
      where: 'Where',
      register: 'Register',
      learnMore: 'Learn More',
      sundayWorship: 'Sunday Worship',
      prayerMeeting: 'Prayer Meeting',
      youthGathering: 'Youth Gathering',
      communityOutreach: 'Community Outreach',
    },
    // Ministries Page
    ministries: {
      title: 'Ministries',
      subtitle: 'Find your place to serve and grow',
      allMinistries: 'All Ministries',
      worship: 'Worship Ministry',
      worshipText: 'Join our worship team in leading the congregation in praise and worship.',
      youth: 'Youth Ministry',
      youthText: 'Empowering the next generation to follow Jesus passionately.',
      children: 'Children Ministry',
      childrenText: 'Teaching children about God\'s love through engaging activities.',
      prayer: 'Prayer Ministry',
      prayerText: 'Interceding for our church, community, and the nations.',
      outreach: 'Outreach Ministry',
      outreachText: 'Sharing the Gospel and serving our community with love.',
      media: 'Media Ministry',
      mediaText: 'Using technology to spread the Gospel and serve the church.',
      joinMinistry: 'Join This Ministry',
    },
    // Give Page
    give: {
      title: 'Give',
      subtitle: 'Support the mission and ministry of Movement Church',
      whyGive: 'Why Give?',
      whyGiveText: 'Your generous giving enables us to spread the Gospel, support our community, and fulfill the Great Commission.',
      oneTimeGift: 'One-Time Gift',
      recurringGift: 'Recurring Gift',
      amount: 'Amount',
      giveNow: 'Give Now',
      otherWays: 'Other Ways to Give',
      bankTransfer: 'Bank Transfer',
      ecocash: 'Ecocash',
      cash: 'In Person',
      contactUs: 'Contact us for details',
    },
    // Contact Page
    contact: {
      title: 'Contact Us',
      subtitle: 'We\'d love to hear from you',
      getInTouch: 'Get In Touch',
      name: 'Your Name',
      email: 'Email Address',
      phone: 'Phone Number',
      message: 'Your Message',
      sendMessage: 'Send Message',
      visitUs: 'Visit Us',
      address: 'Fourth Avenue, Masotsha Ndlovu Way, Parktown, Waterfalls, Harare, Zimbabwe',
      emailUs: 'Email Us',
      callUs: 'Call Us',
      followUs: 'Follow Us',
      serviceTime: 'Service Times',
      sundayMorning: 'Sunday Morning: 10:00 AM',
    },
    // Get Involved Page
    getInvolved: {
      title: 'Get Involved',
      subtitle: 'Find your place in the Movement Church family',
      volunteer: 'Volunteer',
      volunteerText: 'Use your gifts and talents to serve in various ministries.',
      smallGroups: 'Join a Small Group',
      smallGroupsText: 'Connect with others in a small group for fellowship and growth.',
      baptism: 'Get Baptized',
      baptismText: 'Take the next step in your faith journey through baptism.',
      membership: 'Become a Member',
      membershipText: 'Commit to being part of the Movement Church family.',
      serveTeam: 'Join a Serve Team',
      missions: 'Go on a Mission Trip',
      learnMore: 'Learn More',
      signUp: 'Sign Up',
    },
    // Footer
    footer: {
      tagline: 'Teaching the commands of Jesus Christ',
      quickLinks: 'Quick Links',
      ministries: 'Ministries',
      connectWithUs: 'Connect With Us',
      address: 'Address',
      email: 'Email',
      phone: 'Phone',
      serviceTime: 'Service Time',
      sunday: 'Sundays at 10:00 AM',
      rights: '© 2024 Movement Church. All rights reserved.',
      newsletter: 'Subscribe to Newsletter',
      subscribe: 'Subscribe',
    },
  },
  nd: {
    // Navigation (Ndebele)
    nav: {
      home: 'Ikhaya',
      about: 'Ngathi',
      sermons: 'Izintshumayelo',
      events: 'Imicimbi',
      ministries: 'Imisebenzi',
      give: 'Nikela',
      contact: 'Xhumana',
      getInvolved: 'Zibandakanye',
      watchLive: 'Bukela Ngqo',
    },
    // Home Page
    home: {
      welcome: 'Siyakwamukela',
      churchName: 'eBandleni leMovement',
      tagline: 'Ukufundisa Imilayo YekaJesu Kristu',
      mission: 'Sikholwa ngoMthetho Omkhulu',
      joinUs: 'Zihlanganise Lathi',
      watchOnline: 'Bukela Online',
      sundayService: 'Inkonzo YeSonto',
      serviceTime: 'Ngo-10:00 AM Ngesonto Ngalinye',
      serviceLocation: 'Fourth Avenue, Masotsha Ndlovu Way, Parktown',
      liveNow: 'Ngqo Manje',
      upcomingEvents: 'Imicimbi Ezayo',
      latestSermons: 'Izintshumayelo Zakamuva',
      ourMission: 'Umsebenzi Wethu',
      missionText: 'Sizibophezele ekufundiseni imilayo kaJesu Kristu lokugcwalisa uMthetho Omkhulu ngokwenza abafundi bazo zonke izizwe.',
      getConnected: 'Xhumana',
      connectText: 'Sihlanganise ekukhonzeni, ebudlelwaneni nasekukhonzeni umphakathi wethu.',
      visitUs: 'Sivakashele',
    },
    // About Page
    about: {
      title: 'Nge Movement Church',
      subtitle: 'Indaba Yethu, Umbono Lamagugu',
      ourStory: 'Indaba Yethu',
      storyText: 'IBandla leMovement lasungulwa ngenkanuko yokubona impilo ziguqulwa ngamandla eVangeli. Siyimphakathi yabakholwayo abazinikele ekulandeleni uJesu Kristu lokuphila imilayo yakhe.',
      ourVision: 'Umbono Wethu',
      visionText: 'Ukuba yimvuselelo yabafundi abenza abafundi, befundisa njalo bephila imilayo kaJesu Kristu emphakathini wethu langaphezulu.',
      ourValues: 'Amagugu Ethu',
      value1: 'UMthetho Omkhulu',
      value1Text: 'Sizinikele ekugcwaliseni uMthetho Omkhulu ngokwenza abafundi bazo zonke izizwe.',
      value2: 'Ukufundisa KweBhayibheli',
      value2Text: 'Sifundisa futhi silalele imilayo kaJesu Kristu njengoba ivezwe emaWebhini.',
      value3: 'Umphakathi',
      value3Text: 'Sikholwa ebudlelwaneni obungokoqobo lekunakekelana.',
      value4: 'Inkonzo',
      value4Text: 'Sikhonza umphakathi wethu lomhlaba ngothando lukaKristu.',
      leadershipTeam: 'Iqembu Labaholi',
      meetOurPastors: 'Hlanganani Lababelusi Bethu',
    },
    // Sermons Page
    sermons: {
      title: 'Izintshumayelo',
      subtitle: 'Bukela ulalele imilayezo eguqula ukuphila',
      latest: 'Umlayezo Wakamuva',
      allSermons: 'Zonke Izintshumayelo',
      watchNow: 'Bukela Manje',
      series: 'Uchungechunge',
      speaker: 'Umtshumayeli',
      date: 'Usuku',
      duration: 'Isikhathi',
      categories: 'Izigaba',
    },
    // Events Page
    events: {
      title: 'Imicimbi',
      subtitle: 'Sihlanganise emicimbini lemihlanganisweni ezayo',
      upcoming: 'Imicimbi Ezayo',
      past: 'Imicimbi Edlulileyo',
      when: 'Nini',
      where: 'Ngaphi',
      register: 'Bhalisa',
      learnMore: 'Funda Okuningi',
      sundayWorship: 'Ukukhonza NgeseSonto',
      prayerMeeting: 'Umhlangano Wokukhuleka',
      youthGathering: 'Umhlangano Wentsha',
      communityOutreach: 'Ukufinyelela Emphakathini',
    },
    // Ministries Page
    ministries: {
      title: 'Imisebenzi',
      subtitle: 'Thola indawo yakho yokukhonza lokukhula',
      allMinistries: 'Yonke Imisebenzi',
      worship: 'Umsebenzi Wokukhonza',
      worshipText: 'Sihlanganise leqembu lethu lokukhonza ekuholeni ibandla ekudumiseni lasebukhonzeni.',
      youth: 'Umsebenzi Wentsha',
      youthText: 'Ukuthuthukisa isizukulwana esilandelayo ukuthi silandele uJesu ngenkanuko.',
      children: 'Umsebenzi Wabantwana',
      childrenText: 'Ukufundisa abantwana ngothando lukaNkulunkulu ngemisebenzi ehlabahlosile.',
      prayer: 'Umsebenzi Wokukhuleka',
      prayerText: 'Ukukhulekela ibandla lethu, umphakathi, lezizwe.',
      outreach: 'Umsebenzi Wokufinyelela',
      outreachText: 'Ukwabelana ngeVangeli lokukhonza umphakathi wethu ngothando.',
      media: 'Umsebenzi Wemidiya',
      mediaText: 'Ukusebenzisa ubuchwepheshe ukusabalalisa iVangeli lokukhonza ibandla.',
      joinMinistry: 'Hlanganisa Lo Msebenzi',
    },
    // Give Page
    give: {
      title: 'Nikela',
      subtitle: 'Sekela umthetho lomsebenzi we Movement Church',
      whyGive: 'Kungani Nikela?',
      whyGiveText: 'Ukunikela kwakho okuthilela kwenza ukuthi sakwazi ukusabalalisa iVangeli, ukusekela umphakathi wethu, lokugcwalisa uMthetho Omkhulu.',
      oneTimeGift: 'Isipho Sesinye Isikhathi',
      recurringGift: 'Isipho Esiphindaphindako',
      amount: 'Imali',
      giveNow: 'Nikela Manje',
      otherWays: 'Ezinye Izindlela Zokunikela',
      bankTransfer: 'Ukudlulisela Emabhangeni',
      ecocash: 'Ecocash',
      cash: 'Ngqo',
      contactUs: 'Sixhumane ukuze uthole imininingwane',
    },
    // Contact Page
    contact: {
      title: 'Sixhumane',
      subtitle: 'Sifisa ukukuzwa',
      getInTouch: 'Xhumana',
      name: 'Ibizo Lakho',
      email: 'I-imeyili',
      phone: 'Inombolo Yocingo',
      message: 'Umlayezo Wakho',
      sendMessage: 'Thumela Umlayezo',
      visitUs: 'Sivakashele',
      address: 'Fourth Avenue, Masotsha Ndlovu Way, Parktown, Waterfalls, Harare, Zimbabwe',
      emailUs: 'Sithumelele I-imeyili',
      callUs: 'Usishayele',
      followUs: 'Sil andeleni',
      serviceTime: 'Izikhathi Zenkonzo',
      sundayMorning: 'Ekuseni NgeseSonto: 10:00 AM',
    },
    // Get Involved Page
    getInvolved: {
      title: 'Zibandakanye',
      subtitle: 'Thola indawo yakho emdenini we Movement Church',
      volunteer: 'Volontiya',
      volunteerText: 'Sebenzisa izipho zakho lamandla akho ukukhonza kwimisebenzi ehlukahlukene.',
      smallGroups: 'Hlanganisa Iqembu Elincane',
      smallGroupsText: 'Xhumana labanye eqenjini elincane lobudlelwano lokukhula.',
      baptism: 'Bhabhathizwa',
      baptismText: 'Thatha isinyathelo esilandelayo ekuhambeni kokholo lwakho ngokubhabhathizwa.',
      membership: 'Yiba Lilungu',
      membershipText: 'Zinikele ekubeni yingxenye yomndeni we Movement Church.',
      serveTeam: 'Hlanganisa Iqembu Lokukhonza',
      missions: 'Hamba Ngohambo Lomthetho',
      learnMore: 'Funda Okuningi',
      signUp: 'Bhalisa',
    },
    // Footer
    footer: {
      tagline: 'Ukufundisa imilayo kaJesu Kristu',
      quickLinks: 'Izixhumanisi Ezishesha',
      ministries: 'Imisebenzi',
      connectWithUs: 'Xhumana Lathi',
      address: 'Ikheli',
      email: 'I-imeyili',
      phone: 'Ucingo',
      serviceTime: 'Isikhathi Senkonzo',
      sunday: 'Ngesonto ngo-10:00 AM',
      rights: '© 2024 Movement Church. Wonke amalungelo agodliwe.',
      newsletter: 'Bhalisa Encwadini Yezindaba',
      subscribe: 'Bhalisa',
    },
  },
  es: {
    // Navigation (Spanish)
    nav: {
      home: 'Inicio',
      about: 'Nosotros',
      sermons: 'Sermones',
      events: 'Eventos',
      ministries: 'Ministerios',
      give: 'Donar',
      contact: 'Contacto',
      getInvolved: 'Participar',
      watchLive: 'Ver en Vivo',
    },
    // Home Page
    home: {
      welcome: 'Bienvenido a',
      churchName: 'Iglesia Movement',
      tagline: 'Enseñando los Mandamientos de Jesucristo',
      mission: 'Creemos en la Gran Comisión',
      joinUs: 'Únete',
      watchOnline: 'Ver Online',
      sundayService: 'Servicio Dominical',
      serviceTime: '10:00 AM Todos los Domingos',
      serviceLocation: 'Fourth Avenue, Masotsha Ndlovu Way, Parktown',
      liveNow: 'En Vivo Ahora',
      upcomingEvents: 'Próximos Eventos',
      latestSermons: 'Últimos Sermones',
      ourMission: 'Nuestra Misión',
      missionText: 'Estamos comprometidos a enseñar los mandamientos de Jesucristo y cumplir la Gran Comisión haciendo discípulos de todas las naciones.',
      getConnected: 'Conéctate',
      connectText: 'Únete a nosotros en adoración, comunión y servicio a nuestra comunidad.',
      visitUs: 'Visítanos',
    },
    // About Page
    about: {
      title: 'Sobre Iglesia Movement',
      subtitle: 'Nuestra Historia, Visión y Valores',
      ourStory: 'Nuestra Historia',
      storyText: 'Iglesia Movement fue fundada con pasión por ver vidas transformadas por el poder del Evangelio. Somos una comunidad de creyentes comprometidos a seguir a Jesucristo y vivir Sus mandamientos.',
      ourVision: 'Nuestra Visión',
      visionText: 'Ser un movimiento de discípulos haciendo discípulos, enseñando y viviendo los mandamientos de Jesucristo en nuestra comunidad y más allá.',
      ourValues: 'Nuestros Valores',
      value1: 'Gran Comisión',
      value1Text: 'Estamos comprometidos a cumplir la Gran Comisión haciendo discípulos de todas las naciones.',
      value2: 'Enseñanza Bíblica',
      value2Text: 'Enseñamos y obedecemos los mandamientos de Jesucristo revelados en las Escrituras.',
      value3: 'Comunidad',
      value3Text: 'Creemos en la comunión auténtica y el cuidado mutuo.',
      value4: 'Servicio',
      value4Text: 'Servimos a nuestra comunidad y al mundo con el amor de Cristo.',
      leadershipTeam: 'Equipo de Liderazgo',
      meetOurPastors: 'Conoce a Nuestros Pastores',
    },
    // Sermons Page
    sermons: {
      title: 'Sermones',
      subtitle: 'Mira y escucha mensajes que transforman vidas',
      latest: 'Último Mensaje',
      allSermons: 'Todos los Sermones',
      watchNow: 'Ver Ahora',
      series: 'Serie',
      speaker: 'Predicador',
      date: 'Fecha',
      duration: 'Duración',
      categories: 'Categorías',
    },
    // Events Page
    events: {
      title: 'Eventos',
      subtitle: 'Únete a nosotros en próximos eventos y reuniones',
      upcoming: 'Próximos Eventos',
      past: 'Eventos Pasados',
      when: 'Cuándo',
      where: 'Dónde',
      register: 'Registrarse',
      learnMore: 'Saber Más',
      sundayWorship: 'Adoración Dominical',
      prayerMeeting: 'Reunión de Oración',
      youthGathering: 'Reunión de Jóvenes',
      communityOutreach: 'Alcance Comunitario',
    },
    // Ministries Page
    ministries: {
      title: 'Ministerios',
      subtitle: 'Encuentra tu lugar para servir y crecer',
      allMinistries: 'Todos los Ministerios',
      worship: 'Ministerio de Adoración',
      worshipText: 'Únete a nuestro equipo de adoración para guiar a la congregación en alabanza y adoración.',
      youth: 'Ministerio de Jóvenes',
      youthText: 'Empoderando la próxima generación para seguir a Jesús apasionadamente.',
      children: 'Ministerio de Niños',
      childrenText: 'Enseñando a los niños sobre el amor de Dios através de actividades interesantes.',
      prayer: 'Ministerio de Oración',
      prayerText: 'Intercediendo por nuestra iglesia, comunidad y las naciones.',
      outreach: 'Ministerio de Alcance',
      outreachText: 'Compartiendo el Evangelio y sirviendo a nuestra comunidad con amor.',
      media: 'Ministerio de Medios',
      mediaText: 'Usando la tecnología para difundir el Evangelio y servir a la iglesia.',
      joinMinistry: 'Únete a Este Ministerio',
    },
    // Give Page
    give: {
      title: 'Donar',
      subtitle: 'Apoya la misión y ministerio de Iglesia Movement',
      whyGive: '¿Por Qué Donar?',
      whyGiveText: 'Tu generosa donación nos permite difundir el Evangelio, apoyar a nuestra comunidad y cumplir la Gran Comisión.',
      oneTimeGift: 'Donación Única',
      recurringGift: 'Donación Recurrente',
      amount: 'Cantidad',
      giveNow: 'Donar Ahora',
      otherWays: 'Otras Formas de Donar',
      bankTransfer: 'Transferencia Bancaria',
      ecocash: 'Ecocash',
      cash: 'En Persona',
      contactUs: 'Contáctanos para detalles',
    },
    // Contact Page
    contact: {
      title: 'Contáctanos',
      subtitle: 'Nos encantaría saber de ti',
      getInTouch: 'Ponte en Contacto',
      name: 'Tu Nombre',
      email: 'Correo Electrónico',
      phone: 'Número de Teléfono',
      message: 'Tu Mensaje',
      sendMessage: 'Enviar Mensaje',
      visitUs: 'Visítanos',
      address: 'Fourth Avenue, Masotsha Ndlovu Way, Parktown, Waterfalls, Harare, Zimbabwe',
      emailUs: 'Envíanos un Correo',
      callUs: 'Llámanos',
      followUs: 'Síguenos',
      serviceTime: 'Horarios de Servicio',
      sundayMorning: 'Domingo por la Mañana: 10:00 AM',
    },
    // Get Involved Page
    getInvolved: {
      title: 'Participa',
      subtitle: 'Encuentra tu lugar en la familia de Iglesia Movement',
      volunteer: 'Voluntario',
      volunteerText: 'Usa tus dones y talentos para servir en varios ministerios.',
      smallGroups: 'Únete a un Grupo Pequeño',
      smallGroupsText: 'Conéctate con otros en un grupo pequeño para comunión y crecimiento.',
      baptism: 'Bautízate',
      baptismText: 'Da el siguiente paso en tu viaje de fe a través del bautismo.',
      membership: 'Hazte Miembro',
      membershipText: 'Comprométete a ser parte de la familia de Iglesia Movement.',
      serveTeam: 'Únete a un Equipo de Servicio',
      missions: 'Participa en un Viaje Misionero',
      learnMore: 'Saber Más',
      signUp: 'Registrarse',
    },
    // Footer
    footer: {
      tagline: 'Enseñando los mandamientos de Jesucristo',
      quickLinks: 'Enlaces Rápidos',
      ministries: 'Ministerios',
      connectWithUs: 'Conéctate Con Nosotros',
      address: 'Dirección',
      email: 'Correo',
      phone: 'Teléfono',
      serviceTime: 'Horario de Servicio',
      sunday: 'Domingos a las 10:00 AM',
      rights: '© 2024 Iglesia Movement. Todos los derechos reservados.',
      newsletter: 'Suscríbete al Boletín',
      subscribe: 'Suscribirse',
    },
  },
};

export const LanguageProvider = ({ children }) => {
  const [language, setLanguage] = useState('en');

  useEffect(() => {
    const savedLanguage = localStorage.getItem('movement-church-language');
    if (savedLanguage && translations[savedLanguage]) {
      setLanguage(savedLanguage);
    }
  }, []);

  const changeLanguage = (lang) => {
    if (translations[lang]) {
      setLanguage(lang);
      localStorage.setItem('movement-church-language', lang);
    }
  };

  const t = translations[language];

  return (
    <LanguageContext.Provider value={{ language, changeLanguage, t }}>
      {children}
    </LanguageContext.Provider>
  );
};